### asdf
GET http://ddragon.leagueoflegends.com/cdn/11.15.1/data/ko_KR/summoner.json HTTP/1.1

### asdf
GET https://riot:afHIUPzxR1bTDjdlwg8_fg@127.0.0.1:58394/lol-champ-select/v1/session HTTP/1.1

### asdf
GET https://riot:afHIUPzxR1bTDjdlwg8_fg@127.0.0.1:58394/lol-match-history/v1/games/5366765964 HTTP/1.1

### asdf
GET https://riot:afHIUPzxR1bTDjdlwg8_fg@127.0.0.1:58394/lol-match-history/v1/game-timelines/5366765964 HTTP/1.1

### asdf
GET https://riot:afHIUPzxR1bTDjdlwg8_fg@127.0.0.1:58394/lol-match-history/v1/products/lol/current-summoner/matches HTTP/1.1

###
GET https://op.gg/summoner/matches/ajax/detail/teamAnalysis/gameId=5366765964&summonerId=23614482&moreLoad=1 HTTP/1.1

### asdf
GET https://riot:1UZNG1b3YFmx55uS41vukQ@127.0.0.1:55292/lol-summoner/v1/summoners/23614482 HTTP/1.1

### asdf
GET https://riot:wqMq5AupHFiFdMuLidDf0g@127.0.0.1:62371/lol-summoner/v1/current-summoner HTTP/1.1

### asdf
GET https://riot:8acYbYW4PFPJ0Xr3T3l_AA@127.0.0.1:53201/swagger/v2/swagger.json HTTP/1.1

### asdf
GET https://riot:8acYbYW4PFPJ0Xr3T3l_AA@127.0.0.1:53201/lol-champions/v1/inventories/23614482/champions HTTP/1.1

### asdf
GET https://127.0.0.1:2999/swagger/v2/swagger.json HTTP/1.1

### asdf
GET https://riot:1UZNG1b3YFmx55uS41vukQ@127.0.0.1:55292/lol-champ-select/v1/session HTTP/1.1

### asdf
GET https://riot:prfDCZ23tciMsv-QFZ5L7w@127.0.0.1:56497/lol-summoner/v1/current-summoner/ HTTP/1.1

### asdf
GET https://riot:1q3HF5XtoeVlEE_NKIJikg@127.0.0.1:58719/lol-summoner/v2/summoners/?ids=[1,"23614482",3] HTTP/1.1

### asdf
GET https://riot:1q3HF5XtoeVlEE_NKIJikg@127.0.0.1:58719/lol-summoner/v1/summoners/?name=달콤치츄 HTTP/1.1

### asdf
GET https://riot:1q3HF5XtoeVlEE_NKIJikg@127.0.0.1:58719/lol-ranked/v1/current-ranked-stats HTTP/1.1

### asdf
GET https://riot:1q3HF5XtoeVlEE_NKIJikg@127.0.0.1:58719/lol-ranked/v1/ranked-stats/?puuids=["3aaff996-ff86-52f2-9f65-f99d6a690163","3aaff996-ff86-52f2-9f65-f99d6a690164","1c2cdb73-eaa6-5bb7-b67f-ce46ff218191",""] HTTP/1.1

### asdf
GET https://riot:1q3HF5XtoeVlEE_NKIJikg@127.0.0.1:58719/lol-ranked/v2/tiers?queueTypes=["RANKED_SOLO_5x5"]&summonerIds=[23614482] HTTP/1.1

### asdf
PATCH https://riot:1UZNG1b3YFmx55uS41vukQ@127.0.0.1:55292/lol-champ-select/v1/session/actions/13 HTTP/1.1

{
        "actorCellId": 0,
        "championId": 3,
        "completed": false,
        "id": 99,
        "isAllyAction": true,
        "isInProgress": true,
        "pickTurn": 1,
        "type": "pick"
}

### 현재 상태 보기
GET https://riot:afHIUPzxR1bTDjdlwg8_fg@127.0.0.1:58394/lol-gameflow/v1/session HTTP/1.1

### 현재 상태 보기
GET https://riot:afHIUPzxR1bTDjdlwg8_fg@127.0.0.1:58394/lol-gameflow/v1/gameflow-phase HTTP/1.1

### 매치메이킹
GET https://riot:EnZGyMymupMM6IUhHQvd4w@127.0.0.1:58736/lol-matchmaking/v1/search HTTP/1.1

###
GET https://localhost:2999/liveclientdata/playerlist HTTP/1.1

###
POST http://api.lolgo.gg/analyrequest HTTP/1.1
Content-Type: application/json

{
  "matchId":"5463096178"
}

###
GET https://ddragon.leagueoflegends.com/cdn/11.19.1/data/ko_KR/item.json HTTP/1.1
